
default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  database: reddit_development

test:
  <<: *default
  database: reddit_test

production:
  <<: *default
  database: reddit_production
  username: reddit
  password: <%= ENV['REDDIT_DATABASE_PASSWORD'] %>
